### ISSUE TITLE
[Sugestão] Interface Visual

### ISSUE THREAD

**Issue by focamacho** [samuelp88/AterNode#1]
Olá amigo, achei muito interessante seu projeto.
Gostaria de sugerir que fosse implementada a possibilidade de fazer tudo isso por uma interface visual, onde nós só colocaríamos os valores e o programa faria tudo para nós.

Projeto muito bom!
Parabéns!

**Comment by samuelp88** [comment]
Muito obrigado amigo, sugestão muito boa, vou pensar em como implementar isso

**Comment by samuelp88** [comment]
Infelizmente não vai dar amigo, o projeto foi descontinuado

**Comment by focamacho** [comment]
beleza
